import { useEffect, useState } from 'react'
import type { MouseEventHandler } from 'react'
import RandomCard from '@/components/RandomCard'
import Head from 'next/head'
import Header from '@/components/Header'
import AddButton from '@/components/AddButton'

export const getCardFromAPI = async () => {
  const response = await fetch(
    'https://db.ygoprodeck.com/api/v7/randomcard.php'
  )
  const yugiCard: TCard = await response.json()
  return yugiCard
}

const Home = () => {
  const [images, setImages] = useState<Array<TCard>>([])
  const [loading, setLoading] = useState<boolean>(false)

  const addNewCard: MouseEventHandler<HTMLButtonElement> = async (event) => {
    setLoading(true)
    const card: TCard = await getCardFromAPI()
    setImages([...images, card])
    setTimeout(() => {}, 1000)
    setLoading(false)
  }

  return (
    <>
      <Head>
        <title>Random Yu-Gi-Oh! Card | Simón A. Azócar</title>
        <meta
          name='description'
          content='Generated by create next app and tailwind css'
        />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='pt-6 grid place-content-center text-center'>
        <Header />
        <div className='container w-80 mx-auto'>
          <AddButton addNewCard={addNewCard} loading={loading} />
        </div>
        {images.map(({ id, card_images }) => (
          <div className='p-6' key={id}>
            <RandomCard cardImage={card_images[0].image_url} />
          </div>
        ))}
      </main>
    </>
  )
}

export default Home

