import RandomCard from '@/components/RandomCard'
import Head from 'next/head'

export const getStaticProps = async () => {
  const response = await fetch(
    'https://db.ygoprodeck.com/api/v7/randomcard.php'
  )
  const yugiCard: TCard = await response.json()

  return {
    props: {
      yugiCard,
    },
  }
}

const Home = ({ yugiCard }: { yugiCard: TCard }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='pt-6 grid place-content-center text-center'>
        <h1 className='text-3xl font-bold underline'>Hello world!</h1>
        <RandomCard yugiCard={yugiCard} />
      </main>
    </>
  )
}

export default Home
